image_width: 1280
image_height: 720
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1025.88414,     0.     ,   621.07104,
             0.     ,  1027.97109,   371.43172,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.052870, -0.136777, 0.000476, -0.002448, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1024.3645 ,     0.     ,   616.69759,     0.     ,
             0.     ,  1033.18579,   371.14395,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
